GET http://localhost:8080/api/contas-bancarias
###

GET http://localhost:8080/api/contas-bancarias/1
###

POST http://localhost:8080/api/contas-bancarias
Content-Type: application/json

{
    "agencia":"0001",
    "numero": "12349",
    "saldo": 300.0,
    "titular": {
        "id": 8
    }
}
###

PUT http://localhost:8080/api/contas-bancarias/2
Content-Type: application/json

{
    "agencia":"0001",
    "numero": "99999",
    "saldo": 800.0
}
###

DELETE  http://localhost:8080/api/contas-bancarias/1